services:
  server:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - postgres
    restart: always

  mongo:
    image: mongo
    ports:
      - "21771:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: bartar20@CS
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bartar20@CS
      POSTGRES_DB: easycook
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  pg-data: