services:
  server:
    build: .
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      - mongo  

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server

  mongo:
    image: mongo:7
    ports:
      - "21771:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: bartar20@CS
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: