services:
  server:
    build: .
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server

  mongo:
    image: mongo
    # ports:
    #   - "21771:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: bartar20@CS
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres
    # ports:
    #   - "5433:5432"  # Remove this line
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bartar20@CS
      POSTGRES_DB: easycook
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  pg-data: